
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::IdentityType_IdentityAssertions_IdentityAssertion;


our @ISA=qw(XML::Pastor::Builtin::normalizedString);

SIF::AU::Type::IdentityType_IdentityAssertions_IdentityAssertion->mk_accessors( qw(_SchemaName));

# Attribute accessor aliases

sub SchemaName { &_SchemaName; }

SIF::AU::Type::IdentityType_IdentityAssertions_IdentityAssertion->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'SchemaName' => bless( {
                                                     'class' => 'XML::Pastor::Builtin::normalizedString',
                                                     'documentation' => bless( [
                                                                                 bless( {
                                                                                          'text' => 'The name of the field.'
                                                                                        }, 'XML::Pastor::Schema::Documentation' )
                                                                               ], 'Data::HashArray' ),
                                                     'metaClass' => 'SIF::AU::Pastor::Meta',
                                                     'name' => 'SchemaName',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                     'type' => 'normalizedString|http://www.w3.org/2001/XMLSchema',
                                                     'use' => 'required'
                                                   }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'SchemaName'
                         ],
         'base' => 'normalizedString|http://www.w3.org/2001/XMLSchema',
         'baseClasses' => [
                            'XML::Pastor::Builtin::normalizedString'
                          ],
         'class' => 'SIF::AU::Type::IdentityType_IdentityAssertions_IdentityAssertion',
         'contentType' => 'complex',
         'derivedBy' => 'extension',
         'elementInfo' => {},
         'elements' => [],
         'isRedefinable' => 1,
         'isSimpleContent' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'IdentityType_IdentityAssertions_IdentityAssertion',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::IdentityType_IdentityAssertions_IdentityAssertion>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::Builtin::normalizedString>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_SchemaName>(), B<SchemaName>()      - See L<XML::Pastor::Builtin::normalizedString>.

=back


=head1 SEE ALSO

L<XML::Pastor::Builtin::normalizedString>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
