
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::LEAInfoType_LEAContactList_LEAContact;

use SIF::AU::ContactInfo;
use SIF::AU::Type::ContactInfoType;
use SIF::AU::Type::PublishInDirectoryType;

our @ISA=qw(XML::Pastor::ComplexType);

SIF::AU::Type::LEAInfoType_LEAContactList_LEAContact->mk_accessors( qw(PublishInDirectory ContactInfo));

SIF::AU::Type::LEAInfoType_LEAContactList_LEAContact->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SIF::AU::Type::LEAInfoType_LEAContactList_LEAContact',
         'contentType' => 'complex',
         'elementInfo' => {
                            'ContactInfo' => bless( {
                                                    'class' => 'SIF::AU::Type::ContactInfoType',
                                                    'definition' => bless( {
                                                                             'baseClasses' => [
                                                                                                'SIF::AU::Type::ContactInfoType',
                                                                                                'XML::Pastor::Element'
                                                                                              ],
                                                                             'class' => 'SIF::AU::ContactInfo',
                                                                             'isRedefinable' => 1,
                                                                             'metaClass' => 'SIF::AU::Pastor::Meta',
                                                                             'name' => 'ContactInfo',
                                                                             'scope' => 'global',
                                                                             'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                                             'type' => 'ContactInfoType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                                           }, 'XML::Pastor::Schema::Element' ),
                                                    'metaClass' => 'SIF::AU::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'ContactInfo',
                                                    'nameIsAutoGenerated' => 1,
                                                    'ref' => 'ContactInfo|http://www.SIFinfo.org/au/datamodel/1.3',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
                                                  }, 'XML::Pastor::Schema::Element' ),
                            'PublishInDirectory' => bless( {
                                                           'class' => 'SIF::AU::Type::PublishInDirectoryType',
                                                           'documentation' => bless( [
                                                                                       bless( {
                                                                                                'text' => 'Indicates whether or not this LEA contact\'s information should be published in a directory of LEA information.'
                                                                                              }, 'XML::Pastor::Schema::Documentation' )
                                                                                     ], 'Data::HashArray' ),
                                                           'metaClass' => 'SIF::AU::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'PublishInDirectory',
                                                           'nillable' => 'true',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                           'type' => 'PublishInDirectoryType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                         }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'PublishInDirectory',
                         'ContactInfo'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'LEAInfoType_LEAContactList_LEAContact',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::LEAInfoType_LEAContactList_LEAContact>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<ContactInfo>()      - See L<SIF::AU::Type::ContactInfoType>.

=item B<PublishInDirectory>()      - See L<SIF::AU::Type::PublishInDirectoryType>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
