
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::LearningResourceType_Contacts_Contact;

use SIF::AU::Type::AddressType;
use SIF::AU::Type::EmailType;
use SIF::AU::Type::NameType;
use SIF::AU::Type::PhoneNumberType;

our @ISA=qw(XML::Pastor::ComplexType);

SIF::AU::Type::LearningResourceType_Contacts_Contact->mk_accessors( qw(Name Address PhoneNumber Email));

SIF::AU::Type::LearningResourceType_Contacts_Contact->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SIF::AU::Type::LearningResourceType_Contacts_Contact',
         'contentType' => 'complex',
         'elementInfo' => {
                            'Address' => bless( {
                                                'class' => 'SIF::AU::Type::AddressType',
                                                'documentation' => bless( [
                                                                            bless( {
                                                                                     'text' => 'Address of organization or company.'
                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                          ], 'Data::HashArray' ),
                                                'metaClass' => 'SIF::AU::Pastor::Meta',
                                                'minOccurs' => '0',
                                                'name' => 'Address',
                                                'nillable' => 'true',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                'type' => 'AddressType|http://www.SIFinfo.org/au/datamodel/1.3'
                                              }, 'XML::Pastor::Schema::Element' ),
                            'Email' => bless( {
                                              'class' => 'SIF::AU::Type::EmailType',
                                              'documentation' => bless( [
                                                                          bless( {
                                                                                   'text' => 'The email of the organization or company.'
                                                                                 }, 'XML::Pastor::Schema::Documentation' )
                                                                        ], 'Data::HashArray' ),
                                              'metaClass' => 'SIF::AU::Pastor::Meta',
                                              'minOccurs' => '0',
                                              'name' => 'Email',
                                              'nillable' => 'true',
                                              'scope' => 'local',
                                              'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                              'type' => 'EmailType|http://www.SIFinfo.org/au/datamodel/1.3'
                                            }, 'XML::Pastor::Schema::Element' ),
                            'Name' => bless( {
                                             'class' => 'SIF::AU::Type::NameType',
                                             'documentation' => bless( [
                                                                         bless( {
                                                                                  'text' => 'Name of contact person. Use the generic element Name.'
                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                       ], 'Data::HashArray' ),
                                             'metaClass' => 'SIF::AU::Pastor::Meta',
                                             'minOccurs' => '0',
                                             'name' => 'Name',
                                             'nillable' => 'true',
                                             'scope' => 'local',
                                             'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                             'type' => 'NameType|http://www.SIFinfo.org/au/datamodel/1.3'
                                           }, 'XML::Pastor::Schema::Element' ),
                            'PhoneNumber' => bless( {
                                                    'class' => 'SIF::AU::Type::PhoneNumberType',
                                                    'documentation' => bless( [
                                                                                bless( {
                                                                                         'text' => 'Phone number of organization or company.'
                                                                                       }, 'XML::Pastor::Schema::Documentation' )
                                                                              ], 'Data::HashArray' ),
                                                    'metaClass' => 'SIF::AU::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'PhoneNumber',
                                                    'nillable' => 'true',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                    'type' => 'PhoneNumberType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                  }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'Name',
                         'Address',
                         'PhoneNumber',
                         'Email'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'LearningResourceType_Contacts_Contact',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::LearningResourceType_Contacts_Contact>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<Address>()      - See L<SIF::AU::Type::AddressType>.

=item B<Email>()      - See L<SIF::AU::Type::EmailType>.

=item B<Name>()      - See L<SIF::AU::Type::NameType>.

=item B<PhoneNumber>()      - See L<SIF::AU::Type::PhoneNumberType>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
