
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::OnTimeGraduationYearType;


our @ISA=qw(XML::Pastor::Builtin::gYear);

SIF::AU::Type::OnTimeGraduationYearType->XmlSchemaType( bless( {
         'base' => 'gYear|http://www.w3.org/2001/XMLSchema',
         'baseClasses' => [
                            'XML::Pastor::Builtin::gYear'
                          ],
         'class' => 'SIF::AU::Type::OnTimeGraduationYearType',
         'contentType' => 'simple',
         'derivedBy' => 'restriction',
         'documentation' => bless( [
                                     bless( {
                                              'text' => 'First projected graduation year, usually determined when student is accepted into 9th grade (CCYY).'
                                            }, 'XML::Pastor::Schema::Documentation' )
                                   ], 'Data::HashArray' ),
         'isRedefinable' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'OnTimeGraduationYearType',
         'scope' => 'global',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::SimpleType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::OnTimeGraduationYearType>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

First projected graduation year, usually determined when student is accepted into 9th grade (CCYY).


=head1 ISA

This class descends from L<XML::Pastor::Builtin::gYear>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 SEE ALSO

L<XML::Pastor::Builtin::gYear>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
