
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::PublishInDirectoryType;

use SIF::AU::Type::AUCodeSetsYesOrNoCategoryType;

our @ISA=qw(SIF::AU::Type::AUCodeSetsYesOrNoCategoryType);

SIF::AU::Type::PublishInDirectoryType->XmlSchemaType( bless( {
         'base' => 'AUCodeSetsYesOrNoCategoryType|http://www.SIFinfo.org/au/datamodel/1.3',
         'baseClasses' => [
                            'SIF::AU::Type::AUCodeSetsYesOrNoCategoryType'
                          ],
         'class' => 'SIF::AU::Type::PublishInDirectoryType',
         'contentType' => 'simple',
         'derivedBy' => 'restriction',
         'documentation' => bless( [
                                     bless( {
                                              'text' => 'Indicates whether or not information should be published in a directory.'
                                            }, 'XML::Pastor::Schema::Documentation' )
                                   ], 'Data::HashArray' ),
         'isRedefinable' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'PublishInDirectoryType',
         'scope' => 'global',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::SimpleType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::PublishInDirectoryType>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

Indicates whether or not information should be published in a directory.


=head1 ISA

This class descends from L<SIF::AU::Type::AUCodeSetsYesOrNoCategoryType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 SEE ALSO

L<SIF::AU::Type::AUCodeSetsYesOrNoCategoryType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
