
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::SchoolInfoType;

use SIF::AU::Type::AUCodeSetsAustralianStandardClasSIFicationOfReligiousGroupsASCRGType;
use SIF::AU::Type::AUCodeSetsAustralianStandardGeographicalClasSIFicationASGCType;
use SIF::AU::Type::AUCodeSetsFederalElectorateType;
use SIF::AU::Type::AUCodeSetsSchoolCoEdStatusType;
use SIF::AU::Type::AUCodeSetsSchoolLevelType;
use SIF::AU::Type::AUCodeSetsSchoolLocationType;
use SIF::AU::Type::AUCodeSetsSchoolSectorCodeType;
use SIF::AU::Type::AUCodeSetsSchoolSystemType;
use SIF::AU::Type::AUCodeSetsSessionTypeType;
use SIF::AU::Type::AUCodeSetsSystemicStatusType;
use SIF::AU::Type::AUCodeSetsYesOrNoCategoryType;
use SIF::AU::Type::AddressListType;
use SIF::AU::Type::EmailListType;
use SIF::AU::Type::LocalIdType;
use SIF::AU::Type::OperationalStatusType;
use SIF::AU::Type::PhoneNumberListType;
use SIF::AU::Type::PrincipalInfoType;
use SIF::AU::Type::RefIdType;
use SIF::AU::Type::SIF_ExtendedElementsType;
use SIF::AU::Type::SIF_MetadataType;
use SIF::AU::Type::SchoolContactListType;
use SIF::AU::Type::SchoolInfoType_Campus;
use SIF::AU::Type::SchoolInfoType_OtherIdList;
use SIF::AU::Type::SchoolInfoType_OtherLEA;
use SIF::AU::Type::SchoolInfoType_SchoolDistrictLocalId;
use SIF::AU::Type::SchoolInfoType_SchoolFocusList;
use SIF::AU::Type::SchoolInfoType_SchoolGroupList;
use SIF::AU::Type::SchoolURLType;
use SIF::AU::Type::StateProvinceIdType;
use SIF::AU::Type::YearLevelsType;

our @ISA=qw(XML::Pastor::ComplexType);

SIF::AU::Type::SchoolInfoType->mk_accessors( qw(_RefId LocalId StateProvinceId CommonwealthId OtherIdList SchoolName LEAInfoRefId OtherLEA SchoolDistrict SchoolDistrictLocalId SchoolType SchoolFocusList SchoolURL SchoolEmailList PrincipalInfo SchoolContactList AddressList PhoneNumberList SessionType YearLevels ARIA OperationalStatus FederalElectorate Campus SchoolSector IndependentSchool NonGovSystemicStatus System ReligiousAffiliation SchoolGeographicLocation LocalGovernmentArea JurisdictionLowerHouse SLA SchoolCoEdStatus BoardingSchoolStatus Entity_Open Entity_Close SchoolGroupList SIF_Metadata SIF_ExtendedElements));

# Attribute accessor aliases

sub RefId { &_RefId; }

SIF::AU::Type::SchoolInfoType->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'RefId' => bless( {
                                                'class' => 'SIF::AU::Type::RefIdType',
                                                'documentation' => bless( [
                                                                            bless( {
                                                                                     'text' => 'The GUID that identifies this school.'
                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                          ], 'Data::HashArray' ),
                                                'metaClass' => 'SIF::AU::Pastor::Meta',
                                                'name' => 'RefId',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                'type' => 'RefIdType|http://www.SIFinfo.org/au/datamodel/1.3',
                                                'use' => 'required'
                                              }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'RefId'
                         ],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SIF::AU::Type::SchoolInfoType',
         'contentType' => 'complex',
         'documentation' => bless( [
                                     bless( {
                                              'text' => 'This object contains information about the school or campus.'
                                            }, 'XML::Pastor::Schema::Documentation' )
                                   ], 'Data::HashArray' ),
         'elementInfo' => {
                            'ARIA' => bless( {
                                             'class' => 'XML::Pastor::Builtin::decimal',
                                             'documentation' => bless( [
                                                                         bless( {
                                                                                  'text' => 'Accessibility/Remoteness Indicator of Australia.'
                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                       ], 'Data::HashArray' ),
                                             'metaClass' => 'SIF::AU::Pastor::Meta',
                                             'minOccurs' => '0',
                                             'name' => 'ARIA',
                                             'nillable' => 'true',
                                             'scope' => 'local',
                                             'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                             'type' => 'decimal|http://www.w3.org/2001/XMLSchema'
                                           }, 'XML::Pastor::Schema::Element' ),
                            'AddressList' => bless( {
                                                    'class' => 'SIF::AU::Type::AddressListType',
                                                    'documentation' => bless( [
                                                                                bless( {
                                                                                         'text' => 'The school\'s addresses.'
                                                                                       }, 'XML::Pastor::Schema::Documentation' )
                                                                              ], 'Data::HashArray' ),
                                                    'metaClass' => 'SIF::AU::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'AddressList',
                                                    'nillable' => 'true',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                    'type' => 'AddressListType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                  }, 'XML::Pastor::Schema::Element' ),
                            'BoardingSchoolStatus' => bless( {
                                                             'class' => 'SIF::AU::Type::AUCodeSetsYesOrNoCategoryType',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'Is this school a Boarding School?'
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'SIF::AU::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'BoardingSchoolStatus',
                                                             'nillable' => 'true',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                             'type' => 'AUCodeSetsYesOrNoCategoryType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                           }, 'XML::Pastor::Schema::Element' ),
                            'Campus' => bless( {
                                               'class' => 'SIF::AU::Type::SchoolInfoType_Campus',
                                               'metaClass' => 'SIF::AU::Pastor::Meta',
                                               'minOccurs' => '0',
                                               'name' => 'Campus',
                                               'nillable' => 'true',
                                               'scope' => 'local',
                                               'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                               'type' => 'SchoolInfoType_Campus|http://www.SIFinfo.org/au/datamodel/1.3'
                                             }, 'XML::Pastor::Schema::Element' ),
                            'CommonwealthId' => bless( {
                                                       'class' => 'XML::Pastor::Builtin::normalizedString',
                                                       'documentation' => bless( [
                                                                                   bless( {
                                                                                            'text' => 'Commonwealth identifier for this school/campus.'
                                                                                          }, 'XML::Pastor::Schema::Documentation' )
                                                                                 ], 'Data::HashArray' ),
                                                       'metaClass' => 'SIF::AU::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'CommonwealthId',
                                                       'nillable' => 'true',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                       'type' => 'normalizedString|http://www.w3.org/2001/XMLSchema'
                                                     }, 'XML::Pastor::Schema::Element' ),
                            'Entity_Close' => bless( {
                                                     'class' => 'XML::Pastor::Builtin::date',
                                                     'documentation' => bless( [
                                                                                 bless( {
                                                                                          'text' => 'Closing date of entity.  This element is allowed to be omitted and/or null.'
                                                                                        }, 'XML::Pastor::Schema::Documentation' )
                                                                               ], 'Data::HashArray' ),
                                                     'metaClass' => 'SIF::AU::Pastor::Meta',
                                                     'minOccurs' => '0',
                                                     'name' => 'Entity_Close',
                                                     'nillable' => 'true',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                     'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                   }, 'XML::Pastor::Schema::Element' ),
                            'Entity_Open' => bless( {
                                                    'class' => 'XML::Pastor::Builtin::date',
                                                    'documentation' => bless( [
                                                                                bless( {
                                                                                         'text' => 'Opening date of entity.'
                                                                                       }, 'XML::Pastor::Schema::Documentation' )
                                                                              ], 'Data::HashArray' ),
                                                    'metaClass' => 'SIF::AU::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'Entity_Open',
                                                    'nillable' => 'true',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                    'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                  }, 'XML::Pastor::Schema::Element' ),
                            'FederalElectorate' => bless( {
                                                          'class' => 'SIF::AU::Type::AUCodeSetsFederalElectorateType',
                                                          'documentation' => bless( [
                                                                                      bless( {
                                                                                               'text' => 'Australian Federal Electorate.'
                                                                                             }, 'XML::Pastor::Schema::Documentation' )
                                                                                    ], 'Data::HashArray' ),
                                                          'metaClass' => 'SIF::AU::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'FederalElectorate',
                                                          'nillable' => 'true',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                          'type' => 'AUCodeSetsFederalElectorateType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                        }, 'XML::Pastor::Schema::Element' ),
                            'IndependentSchool' => bless( {
                                                          'class' => 'SIF::AU::Type::AUCodeSetsYesOrNoCategoryType',
                                                          'documentation' => bless( [
                                                                                      bless( {
                                                                                               'text' => 'Indicator as to whether school is an independent school (as opposed to government or catholic school).'
                                                                                             }, 'XML::Pastor::Schema::Documentation' )
                                                                                    ], 'Data::HashArray' ),
                                                          'metaClass' => 'SIF::AU::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'IndependentSchool',
                                                          'nillable' => 'true',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                          'type' => 'AUCodeSetsYesOrNoCategoryType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                        }, 'XML::Pastor::Schema::Element' ),
                            'JurisdictionLowerHouse' => bless( {
                                                               'class' => 'XML::Pastor::Builtin::normalizedString',
                                                               'documentation' => bless( [
                                                                                           bless( {
                                                                                                    'text' => 'Lower House area  that the school/campus  belongs to.'
                                                                                                  }, 'XML::Pastor::Schema::Documentation' )
                                                                                         ], 'Data::HashArray' ),
                                                               'metaClass' => 'SIF::AU::Pastor::Meta',
                                                               'minOccurs' => '0',
                                                               'name' => 'JurisdictionLowerHouse',
                                                               'nillable' => 'true',
                                                               'scope' => 'local',
                                                               'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                               'type' => 'normalizedString|http://www.w3.org/2001/XMLSchema'
                                                             }, 'XML::Pastor::Schema::Element' ),
                            'LEAInfoRefId' => bless( {
                                                     'class' => 'SIF::AU::Type::RefIdType',
                                                     'documentation' => bless( [
                                                                                 bless( {
                                                                                          'text' => 'The ID (GUID) that references the school district of which this school is a member.'
                                                                                        }, 'XML::Pastor::Schema::Documentation' )
                                                                               ], 'Data::HashArray' ),
                                                     'metaClass' => 'SIF::AU::Pastor::Meta',
                                                     'minOccurs' => '0',
                                                     'name' => 'LEAInfoRefId',
                                                     'nillable' => 'true',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                     'type' => 'RefIdType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                   }, 'XML::Pastor::Schema::Element' ),
                            'LocalGovernmentArea' => bless( {
                                                            'class' => 'XML::Pastor::Builtin::normalizedString',
                                                            'documentation' => bless( [
                                                                                        bless( {
                                                                                                 'text' => 'LocalGovernmentArea that that school/campus is located in.'
                                                                                               }, 'XML::Pastor::Schema::Documentation' )
                                                                                      ], 'Data::HashArray' ),
                                                            'metaClass' => 'SIF::AU::Pastor::Meta',
                                                            'minOccurs' => '0',
                                                            'name' => 'LocalGovernmentArea',
                                                            'nillable' => 'true',
                                                            'scope' => 'local',
                                                            'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                            'type' => 'normalizedString|http://www.w3.org/2001/XMLSchema'
                                                          }, 'XML::Pastor::Schema::Element' ),
                            'LocalId' => bless( {
                                                'class' => 'SIF::AU::Type::LocalIdType',
                                                'documentation' => bless( [
                                                                            bless( {
                                                                                     'text' => 'The locally-assigned identifier for this school.'
                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                          ], 'Data::HashArray' ),
                                                'metaClass' => 'SIF::AU::Pastor::Meta',
                                                'minOccurs' => '0',
                                                'name' => 'LocalId',
                                                'nillable' => 'true',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                'type' => 'LocalIdType|http://www.SIFinfo.org/au/datamodel/1.3'
                                              }, 'XML::Pastor::Schema::Element' ),
                            'NonGovSystemicStatus' => bless( {
                                                             'class' => 'SIF::AU::Type::AUCodeSetsSystemicStatusType',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'Used to clarify a non-government school\'s systemic status. Either Systemic or Non-Systemic.'
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'SIF::AU::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'NonGovSystemicStatus',
                                                             'nillable' => 'true',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                             'type' => 'AUCodeSetsSystemicStatusType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                           }, 'XML::Pastor::Schema::Element' ),
                            'OperationalStatus' => bless( {
                                                          'class' => 'SIF::AU::Type::OperationalStatusType',
                                                          'documentation' => bless( [
                                                                                      bless( {
                                                                                               'text' => 'Operational condition of a school.'
                                                                                             }, 'XML::Pastor::Schema::Documentation' )
                                                                                    ], 'Data::HashArray' ),
                                                          'metaClass' => 'SIF::AU::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'OperationalStatus',
                                                          'nillable' => 'true',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                          'type' => 'OperationalStatusType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                        }, 'XML::Pastor::Schema::Element' ),
                            'OtherIdList' => bless( {
                                                    'class' => 'SIF::AU::Type::SchoolInfoType_OtherIdList',
                                                    'metaClass' => 'SIF::AU::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'OtherIdList',
                                                    'nillable' => 'true',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                    'type' => 'SchoolInfoType_OtherIdList|http://www.SIFinfo.org/au/datamodel/1.3'
                                                  }, 'XML::Pastor::Schema::Element' ),
                            'OtherLEA' => bless( {
                                                 'class' => 'SIF::AU::Type::SchoolInfoType_OtherLEA',
                                                 'metaClass' => 'SIF::AU::Pastor::Meta',
                                                 'minOccurs' => '0',
                                                 'name' => 'OtherLEA',
                                                 'nillable' => 'true',
                                                 'scope' => 'local',
                                                 'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                 'type' => 'SchoolInfoType_OtherLEA|http://www.SIFinfo.org/au/datamodel/1.3'
                                               }, 'XML::Pastor::Schema::Element' ),
                            'PhoneNumberList' => bless( {
                                                        'class' => 'SIF::AU::Type::PhoneNumberListType',
                                                        'documentation' => bless( [
                                                                                    bless( {
                                                                                             'text' => 'The school\'s phone numbers.'
                                                                                           }, 'XML::Pastor::Schema::Documentation' )
                                                                                  ], 'Data::HashArray' ),
                                                        'metaClass' => 'SIF::AU::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'PhoneNumberList',
                                                        'nillable' => 'true',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                        'type' => 'PhoneNumberListType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                      }, 'XML::Pastor::Schema::Element' ),
                            'PrincipalInfo' => bless( {
                                                      'class' => 'SIF::AU::Type::PrincipalInfoType',
                                                      'documentation' => bless( [
                                                                                  bless( {
                                                                                           'text' => 'Information about the campus or school principal.'
                                                                                         }, 'XML::Pastor::Schema::Documentation' )
                                                                                ], 'Data::HashArray' ),
                                                      'metaClass' => 'SIF::AU::Pastor::Meta',
                                                      'minOccurs' => '0',
                                                      'name' => 'PrincipalInfo',
                                                      'nillable' => 'true',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                      'type' => 'PrincipalInfoType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                    }, 'XML::Pastor::Schema::Element' ),
                            'ReligiousAffiliation' => bless( {
                                                             'class' => 'SIF::AU::Type::AUCodeSetsAustralianStandardClasSIFicationOfReligiousGroupsASCRGType',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'Religious affiliation (if any).'
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'SIF::AU::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'ReligiousAffiliation',
                                                             'nillable' => 'true',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                             'type' => 'AUCodeSetsAustralianStandardClasSIFicationOfReligiousGroupsASCRGType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                           }, 'XML::Pastor::Schema::Element' ),
                            'SIF_ExtendedElements' => bless( {
                                                             'class' => 'SIF::AU::Type::SIF_ExtendedElementsType',
                                                             'metaClass' => 'SIF::AU::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'SIF_ExtendedElements',
                                                             'nillable' => 'true',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                             'type' => 'SIF_ExtendedElementsType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                           }, 'XML::Pastor::Schema::Element' ),
                            'SIF_Metadata' => bless( {
                                                     'class' => 'SIF::AU::Type::SIF_MetadataType',
                                                     'metaClass' => 'SIF::AU::Pastor::Meta',
                                                     'minOccurs' => '0',
                                                     'name' => 'SIF_Metadata',
                                                     'nillable' => 'true',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                     'type' => 'SIF_MetadataType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                   }, 'XML::Pastor::Schema::Element' ),
                            'SLA' => bless( {
                                            'class' => 'SIF::AU::Type::AUCodeSetsAustralianStandardGeographicalClasSIFicationASGCType',
                                            'documentation' => bless( [
                                                                        bless( {
                                                                                 'text' => 'Statistical Local Area that the school/campus belongs to.'
                                                                               }, 'XML::Pastor::Schema::Documentation' )
                                                                      ], 'Data::HashArray' ),
                                            'metaClass' => 'SIF::AU::Pastor::Meta',
                                            'minOccurs' => '0',
                                            'name' => 'SLA',
                                            'nillable' => 'true',
                                            'scope' => 'local',
                                            'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                            'type' => 'AUCodeSetsAustralianStandardGeographicalClasSIFicationASGCType|http://www.SIFinfo.org/au/datamodel/1.3'
                                          }, 'XML::Pastor::Schema::Element' ),
                            'SchoolCoEdStatus' => bless( {
                                                         'class' => 'SIF::AU::Type::AUCodeSetsSchoolCoEdStatusType',
                                                         'documentation' => bless( [
                                                                                     bless( {
                                                                                              'text' => 'Gender of student population.'
                                                                                            }, 'XML::Pastor::Schema::Documentation' )
                                                                                   ], 'Data::HashArray' ),
                                                         'metaClass' => 'SIF::AU::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'SchoolCoEdStatus',
                                                         'nillable' => 'true',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                         'type' => 'AUCodeSetsSchoolCoEdStatusType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                       }, 'XML::Pastor::Schema::Element' ),
                            'SchoolContactList' => bless( {
                                                          'class' => 'SIF::AU::Type::SchoolContactListType',
                                                          'documentation' => bless( [
                                                                                      bless( {
                                                                                               'text' => 'A list of contact persons associated with a school.'
                                                                                             }, 'XML::Pastor::Schema::Documentation' )
                                                                                    ], 'Data::HashArray' ),
                                                          'metaClass' => 'SIF::AU::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'SchoolContactList',
                                                          'nillable' => 'true',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                          'type' => 'SchoolContactListType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                        }, 'XML::Pastor::Schema::Element' ),
                            'SchoolDistrict' => bless( {
                                                       'class' => 'XML::Pastor::Builtin::normalizedString',
                                                       'documentation' => bless( [
                                                                                   bless( {
                                                                                            'text' => 'The school district of which this school/campus is a member. Equivalent to DEECD Region.'
                                                                                          }, 'XML::Pastor::Schema::Documentation' )
                                                                                 ], 'Data::HashArray' ),
                                                       'metaClass' => 'SIF::AU::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'SchoolDistrict',
                                                       'nillable' => 'true',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                       'type' => 'normalizedString|http://www.w3.org/2001/XMLSchema'
                                                     }, 'XML::Pastor::Schema::Element' ),
                            'SchoolDistrictLocalId' => bless( {
                                                              'class' => 'SIF::AU::Type::SchoolInfoType_SchoolDistrictLocalId',
                                                              'metaClass' => 'SIF::AU::Pastor::Meta',
                                                              'minOccurs' => '0',
                                                              'name' => 'SchoolDistrictLocalId',
                                                              'nillable' => 'true',
                                                              'scope' => 'local',
                                                              'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                              'type' => 'SchoolInfoType_SchoolDistrictLocalId|http://www.SIFinfo.org/au/datamodel/1.3'
                                                            }, 'XML::Pastor::Schema::Element' ),
                            'SchoolEmailList' => bless( {
                                                        'class' => 'SIF::AU::Type::EmailListType',
                                                        'documentation' => bless( [
                                                                                    bless( {
                                                                                             'text' => 'List of contact emails for the school.'
                                                                                           }, 'XML::Pastor::Schema::Documentation' )
                                                                                  ], 'Data::HashArray' ),
                                                        'metaClass' => 'SIF::AU::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'SchoolEmailList',
                                                        'nillable' => 'true',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                        'type' => 'EmailListType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                      }, 'XML::Pastor::Schema::Element' ),
                            'SchoolFocusList' => bless( {
                                                        'class' => 'SIF::AU::Type::SchoolInfoType_SchoolFocusList',
                                                        'metaClass' => 'SIF::AU::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'SchoolFocusList',
                                                        'nillable' => 'true',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                        'type' => 'SchoolInfoType_SchoolFocusList|http://www.SIFinfo.org/au/datamodel/1.3'
                                                      }, 'XML::Pastor::Schema::Element' ),
                            'SchoolGeographicLocation' => bless( {
                                                                 'class' => 'SIF::AU::Type::AUCodeSetsSchoolLocationType',
                                                                 'documentation' => bless( [
                                                                                             bless( {
                                                                                                      'text' => 'School Location from MCEETCYA.'
                                                                                                    }, 'XML::Pastor::Schema::Documentation' )
                                                                                           ], 'Data::HashArray' ),
                                                                 'metaClass' => 'SIF::AU::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'SchoolGeographicLocation',
                                                                 'nillable' => 'true',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                                 'type' => 'AUCodeSetsSchoolLocationType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                               }, 'XML::Pastor::Schema::Element' ),
                            'SchoolGroupList' => bless( {
                                                        'class' => 'SIF::AU::Type::SchoolInfoType_SchoolGroupList',
                                                        'metaClass' => 'SIF::AU::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'SchoolGroupList',
                                                        'nillable' => 'true',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                        'type' => 'SchoolInfoType_SchoolGroupList|http://www.SIFinfo.org/au/datamodel/1.3'
                                                      }, 'XML::Pastor::Schema::Element' ),
                            'SchoolName' => bless( {
                                                   'class' => 'XML::Pastor::Builtin::normalizedString',
                                                   'documentation' => bless( [
                                                                               bless( {
                                                                                        'text' => 'Name of school/campus.'
                                                                                      }, 'XML::Pastor::Schema::Documentation' )
                                                                             ], 'Data::HashArray' ),
                                                   'metaClass' => 'SIF::AU::Pastor::Meta',
                                                   'minOccurs' => '0',
                                                   'name' => 'SchoolName',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                   'type' => 'normalizedString|http://www.w3.org/2001/XMLSchema'
                                                 }, 'XML::Pastor::Schema::Element' ),
                            'SchoolSector' => bless( {
                                                     'class' => 'SIF::AU::Type::AUCodeSetsSchoolSectorCodeType',
                                                     'documentation' => bless( [
                                                                                 bless( {
                                                                                          'text' => '(Government, or Non-Government).'
                                                                                        }, 'XML::Pastor::Schema::Documentation' )
                                                                               ], 'Data::HashArray' ),
                                                     'metaClass' => 'SIF::AU::Pastor::Meta',
                                                     'minOccurs' => '0',
                                                     'name' => 'SchoolSector',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                     'type' => 'AUCodeSetsSchoolSectorCodeType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                   }, 'XML::Pastor::Schema::Element' ),
                            'SchoolType' => bless( {
                                                   'class' => 'SIF::AU::Type::AUCodeSetsSchoolLevelType',
                                                   'documentation' => bless( [
                                                                               bless( {
                                                                                        'text' => 'An indication of the level of the educational institution.'
                                                                                      }, 'XML::Pastor::Schema::Documentation' )
                                                                             ], 'Data::HashArray' ),
                                                   'metaClass' => 'SIF::AU::Pastor::Meta',
                                                   'minOccurs' => '0',
                                                   'name' => 'SchoolType',
                                                   'nillable' => 'true',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                   'type' => 'AUCodeSetsSchoolLevelType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                 }, 'XML::Pastor::Schema::Element' ),
                            'SchoolURL' => bless( {
                                                  'class' => 'SIF::AU::Type::SchoolURLType',
                                                  'documentation' => bless( [
                                                                              bless( {
                                                                                       'text' => 'URL for the school.'
                                                                                     }, 'XML::Pastor::Schema::Documentation' )
                                                                            ], 'Data::HashArray' ),
                                                  'metaClass' => 'SIF::AU::Pastor::Meta',
                                                  'minOccurs' => '0',
                                                  'name' => 'SchoolURL',
                                                  'nillable' => 'true',
                                                  'scope' => 'local',
                                                  'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                  'type' => 'SchoolURLType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                }, 'XML::Pastor::Schema::Element' ),
                            'SessionType' => bless( {
                                                    'class' => 'SIF::AU::Type::AUCodeSetsSessionTypeType',
                                                    'documentation' => bless( [
                                                                                bless( {
                                                                                         'text' => 'Code that specifies the session type.'
                                                                                       }, 'XML::Pastor::Schema::Documentation' )
                                                                              ], 'Data::HashArray' ),
                                                    'metaClass' => 'SIF::AU::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'SessionType',
                                                    'nillable' => 'true',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                    'type' => 'AUCodeSetsSessionTypeType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                  }, 'XML::Pastor::Schema::Element' ),
                            'StateProvinceId' => bless( {
                                                        'class' => 'SIF::AU::Type::StateProvinceIdType',
                                                        'documentation' => bless( [
                                                                                    bless( {
                                                                                             'text' => 'The state-assigned identifier for this school.'
                                                                                           }, 'XML::Pastor::Schema::Documentation' )
                                                                                  ], 'Data::HashArray' ),
                                                        'metaClass' => 'SIF::AU::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'StateProvinceId',
                                                        'nillable' => 'true',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                        'type' => 'StateProvinceIdType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                      }, 'XML::Pastor::Schema::Element' ),
                            'System' => bless( {
                                               'class' => 'SIF::AU::Type::AUCodeSetsSchoolSystemType',
                                               'documentation' => bless( [
                                                                           bless( {
                                                                                    'text' => 'System if a systemic school.'
                                                                                  }, 'XML::Pastor::Schema::Documentation' )
                                                                         ], 'Data::HashArray' ),
                                               'metaClass' => 'SIF::AU::Pastor::Meta',
                                               'minOccurs' => '0',
                                               'name' => 'System',
                                               'nillable' => 'true',
                                               'scope' => 'local',
                                               'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                               'type' => 'AUCodeSetsSchoolSystemType|http://www.SIFinfo.org/au/datamodel/1.3'
                                             }, 'XML::Pastor::Schema::Element' ),
                            'YearLevels' => bless( {
                                                   'class' => 'SIF::AU::Type::YearLevelsType',
                                                   'documentation' => bless( [
                                                                               bless( {
                                                                                        'text' => 'List of year levels offered by the school.'
                                                                                      }, 'XML::Pastor::Schema::Documentation' )
                                                                             ], 'Data::HashArray' ),
                                                   'metaClass' => 'SIF::AU::Pastor::Meta',
                                                   'minOccurs' => '0',
                                                   'name' => 'YearLevels',
                                                   'nillable' => 'true',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                   'type' => 'YearLevelsType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                 }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'LocalId',
                         'StateProvinceId',
                         'CommonwealthId',
                         'OtherIdList',
                         'SchoolName',
                         'LEAInfoRefId',
                         'OtherLEA',
                         'SchoolDistrict',
                         'SchoolDistrictLocalId',
                         'SchoolType',
                         'SchoolFocusList',
                         'SchoolURL',
                         'SchoolEmailList',
                         'PrincipalInfo',
                         'SchoolContactList',
                         'AddressList',
                         'PhoneNumberList',
                         'SessionType',
                         'YearLevels',
                         'ARIA',
                         'OperationalStatus',
                         'FederalElectorate',
                         'Campus',
                         'SchoolSector',
                         'IndependentSchool',
                         'NonGovSystemicStatus',
                         'System',
                         'ReligiousAffiliation',
                         'SchoolGeographicLocation',
                         'LocalGovernmentArea',
                         'JurisdictionLowerHouse',
                         'SLA',
                         'SchoolCoEdStatus',
                         'BoardingSchoolStatus',
                         'Entity_Open',
                         'Entity_Close',
                         'SchoolGroupList',
                         'SIF_Metadata',
                         'SIF_ExtendedElements'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'SchoolInfoType',
         'scope' => 'global',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::SchoolInfoType>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

This object contains information about the school or campus.


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_RefId>(), B<RefId>()      - See L<SIF::AU::Type::RefIdType>.

=back


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<ARIA>()      - See L<XML::Pastor::Builtin::decimal>.

=item B<AddressList>()      - See L<SIF::AU::Type::AddressListType>.

=item B<BoardingSchoolStatus>()      - See L<SIF::AU::Type::AUCodeSetsYesOrNoCategoryType>.

=item B<Campus>()      - See L<SIF::AU::Type::SchoolInfoType_Campus>.

=item B<CommonwealthId>()      - See L<XML::Pastor::Builtin::normalizedString>.

=item B<Entity_Close>()      - See L<XML::Pastor::Builtin::date>.

=item B<Entity_Open>()      - See L<XML::Pastor::Builtin::date>.

=item B<FederalElectorate>()      - See L<SIF::AU::Type::AUCodeSetsFederalElectorateType>.

=item B<IndependentSchool>()      - See L<SIF::AU::Type::AUCodeSetsYesOrNoCategoryType>.

=item B<JurisdictionLowerHouse>()      - See L<XML::Pastor::Builtin::normalizedString>.

=item B<LEAInfoRefId>()      - See L<SIF::AU::Type::RefIdType>.

=item B<LocalGovernmentArea>()      - See L<XML::Pastor::Builtin::normalizedString>.

=item B<LocalId>()      - See L<SIF::AU::Type::LocalIdType>.

=item B<NonGovSystemicStatus>()      - See L<SIF::AU::Type::AUCodeSetsSystemicStatusType>.

=item B<OperationalStatus>()      - See L<SIF::AU::Type::OperationalStatusType>.

=item B<OtherIdList>()      - See L<SIF::AU::Type::SchoolInfoType_OtherIdList>.

=item B<OtherLEA>()      - See L<SIF::AU::Type::SchoolInfoType_OtherLEA>.

=item B<PhoneNumberList>()      - See L<SIF::AU::Type::PhoneNumberListType>.

=item B<PrincipalInfo>()      - See L<SIF::AU::Type::PrincipalInfoType>.

=item B<ReligiousAffiliation>()      - See L<SIF::AU::Type::AUCodeSetsAustralianStandardClasSIFicationOfReligiousGroupsASCRGType>.

=item B<SIF_ExtendedElements>()      - See L<SIF::AU::Type::SIF_ExtendedElementsType>.

=item B<SIF_Metadata>()      - See L<SIF::AU::Type::SIF_MetadataType>.

=item B<SLA>()      - See L<SIF::AU::Type::AUCodeSetsAustralianStandardGeographicalClasSIFicationASGCType>.

=item B<SchoolCoEdStatus>()      - See L<SIF::AU::Type::AUCodeSetsSchoolCoEdStatusType>.

=item B<SchoolContactList>()      - See L<SIF::AU::Type::SchoolContactListType>.

=item B<SchoolDistrict>()      - See L<XML::Pastor::Builtin::normalizedString>.

=item B<SchoolDistrictLocalId>()      - See L<SIF::AU::Type::SchoolInfoType_SchoolDistrictLocalId>.

=item B<SchoolEmailList>()      - See L<SIF::AU::Type::EmailListType>.

=item B<SchoolFocusList>()      - See L<SIF::AU::Type::SchoolInfoType_SchoolFocusList>.

=item B<SchoolGeographicLocation>()      - See L<SIF::AU::Type::AUCodeSetsSchoolLocationType>.

=item B<SchoolGroupList>()      - See L<SIF::AU::Type::SchoolInfoType_SchoolGroupList>.

=item B<SchoolName>()      - See L<XML::Pastor::Builtin::normalizedString>.

=item B<SchoolSector>()      - See L<SIF::AU::Type::AUCodeSetsSchoolSectorCodeType>.

=item B<SchoolType>()      - See L<SIF::AU::Type::AUCodeSetsSchoolLevelType>.

=item B<SchoolURL>()      - See L<SIF::AU::Type::SchoolURLType>.

=item B<SessionType>()      - See L<SIF::AU::Type::AUCodeSetsSessionTypeType>.

=item B<StateProvinceId>()      - See L<SIF::AU::Type::StateProvinceIdType>.

=item B<System>()      - See L<SIF::AU::Type::AUCodeSetsSchoolSystemType>.

=item B<YearLevels>()      - See L<SIF::AU::Type::YearLevelsType>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
