
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::SIF3AssessmentAssetType_AssetIdentifiers_AssetIdentifier;

use SIF::AU::Type::SIF3AssessmentAssetType_AssetIdentifiers_AssetIdentifier_AssetIdType;

our @ISA=qw(XML::Pastor::Builtin::normalizedString);

SIF::AU::Type::SIF3AssessmentAssetType_AssetIdentifiers_AssetIdentifier->mk_accessors( qw(_AssetIdType));

# Attribute accessor aliases

sub AssetIdType { &_AssetIdType; }

SIF::AU::Type::SIF3AssessmentAssetType_AssetIdentifiers_AssetIdentifier->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'AssetIdType' => bless( {
                                                      'class' => 'SIF::AU::Type::SIF3AssessmentAssetType_AssetIdentifiers_AssetIdentifier_AssetIdType',
                                                      'documentation' => bless( [
                                                                                  bless( {
                                                                                           'text' => 'The type of identifier that is provided for this asset.'
                                                                                         }, 'XML::Pastor::Schema::Documentation' )
                                                                                ], 'Data::HashArray' ),
                                                      'metaClass' => 'SIF::AU::Pastor::Meta',
                                                      'name' => 'AssetIdType',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                      'type' => 'SIF3AssessmentAssetType_AssetIdentifiers_AssetIdentifier_AssetIdType|http://www.SIFinfo.org/au/datamodel/1.3',
                                                      'use' => 'optional'
                                                    }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'AssetIdType'
                         ],
         'base' => 'normalizedString|http://www.w3.org/2001/XMLSchema',
         'baseClasses' => [
                            'XML::Pastor::Builtin::normalizedString'
                          ],
         'class' => 'SIF::AU::Type::SIF3AssessmentAssetType_AssetIdentifiers_AssetIdentifier',
         'contentType' => 'complex',
         'derivedBy' => 'extension',
         'elementInfo' => {},
         'elements' => [],
         'isRedefinable' => 1,
         'isSimpleContent' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'SIF3AssessmentAssetType_AssetIdentifiers_AssetIdentifier',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::SIF3AssessmentAssetType_AssetIdentifiers_AssetIdentifier>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::Builtin::normalizedString>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_AssetIdType>(), B<AssetIdType>()      - See L<SIF::AU::Type::SIF3AssessmentAssetType_AssetIdentifiers_AssetIdentifier_AssetIdType>.

=back


=head1 SEE ALSO

L<XML::Pastor::Builtin::normalizedString>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
