
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::SIF3AssessmentScoreTableType_ScoreValues_ScoreValue_DerivedValue;

use SIF::AU::Type::AUCodeSetsAssessmentReportingMethodType;

our @ISA=qw(XML::Pastor::Builtin::token);

SIF::AU::Type::SIF3AssessmentScoreTableType_ScoreValues_ScoreValue_DerivedValue->mk_accessors( qw(_ToScoreMetric));

# Attribute accessor aliases

sub ToScoreMetric { &_ToScoreMetric; }

SIF::AU::Type::SIF3AssessmentScoreTableType_ScoreValues_ScoreValue_DerivedValue->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'ToScoreMetric' => bless( {
                                                        'class' => 'SIF::AU::Type::AUCodeSetsAssessmentReportingMethodType',
                                                        'documentation' => bless( [
                                                                                    bless( {
                                                                                             'text' => 'Indicates the score metric that is being derived by this table. For example, if this score table is deriving a scaled score, then this will be the scale score metric (3479). '
                                                                                           }, 'XML::Pastor::Schema::Documentation' )
                                                                                  ], 'Data::HashArray' ),
                                                        'metaClass' => 'SIF::AU::Pastor::Meta',
                                                        'name' => 'ToScoreMetric',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                        'type' => 'AUCodeSetsAssessmentReportingMethodType|http://www.SIFinfo.org/au/datamodel/1.3',
                                                        'use' => 'required'
                                                      }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'ToScoreMetric'
                         ],
         'base' => 'token|http://www.w3.org/2001/XMLSchema',
         'baseClasses' => [
                            'XML::Pastor::Builtin::token'
                          ],
         'class' => 'SIF::AU::Type::SIF3AssessmentScoreTableType_ScoreValues_ScoreValue_DerivedValue',
         'contentType' => 'complex',
         'derivedBy' => 'extension',
         'elementInfo' => {},
         'elements' => [],
         'isRedefinable' => 1,
         'isSimpleContent' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'SIF3AssessmentScoreTableType_ScoreValues_ScoreValue_DerivedValue',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::SIF3AssessmentScoreTableType_ScoreValues_ScoreValue_DerivedValue>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::Builtin::token>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_ToScoreMetric>(), B<ToScoreMetric>()      - See L<SIF::AU::Type::AUCodeSetsAssessmentReportingMethodType>.

=back


=head1 SEE ALSO

L<XML::Pastor::Builtin::token>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
