
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::SIF3StudentResponseSetType_Items_Item_Comments;

use SIF::AU::Type::SIF3StudentResponseSetType_Items_Item_Comments_Comment;

our @ISA=qw(XML::Pastor::ComplexType);

SIF::AU::Type::SIF3StudentResponseSetType_Items_Item_Comments->mk_accessors( qw(Comment));

SIF::AU::Type::SIF3StudentResponseSetType_Items_Item_Comments->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SIF::AU::Type::SIF3StudentResponseSetType_Items_Item_Comments',
         'contentType' => 'complex',
         'elementInfo' => {
                            'Comment' => bless( {
                                                'class' => 'SIF::AU::Type::SIF3StudentResponseSetType_Items_Item_Comments_Comment',
                                                'maxOccurs' => 'unbounded',
                                                'metaClass' => 'SIF::AU::Pastor::Meta',
                                                'minOccurs' => '0',
                                                'name' => 'Comment',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                'type' => 'SIF3StudentResponseSetType_Items_Item_Comments_Comment|http://www.SIFinfo.org/au/datamodel/1.3'
                                              }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'Comment'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'SIF3StudentResponseSetType_Items_Item_Comments',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::SIF3StudentResponseSetType_Items_Item_Comments>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<Comment>()      - See L<SIF::AU::Type::SIF3StudentResponseSetType_Items_Item_Comments_Comment>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
