
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::SIF_QueryDataModelType_SIF_ConditionGroup_SIF_Conditions_SIF_Condition;

use SIF::AU::Type::SIF_QueryDataModelType_SIF_ConditionGroup_SIF_Conditions_SIF_Condition_SIF_Operator;

our @ISA=qw(XML::Pastor::ComplexType);

SIF::AU::Type::SIF_QueryDataModelType_SIF_ConditionGroup_SIF_Conditions_SIF_Condition->mk_accessors( qw(SIF_Element SIF_Operator SIF_Value));

SIF::AU::Type::SIF_QueryDataModelType_SIF_ConditionGroup_SIF_Conditions_SIF_Condition->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SIF::AU::Type::SIF_QueryDataModelType_SIF_ConditionGroup_SIF_Conditions_SIF_Condition',
         'contentType' => 'complex',
         'elementInfo' => {
                            'SIF_Element' => bless( {
                                                    'class' => 'XML::Pastor::Builtin::normalizedString',
                                                    'documentation' => bless( [
                                                                                bless( {
                                                                                         'text' => 'This is the element/attribute being queried.  See below for syntax.'
                                                                                       }, 'XML::Pastor::Schema::Documentation' )
                                                                              ], 'Data::HashArray' ),
                                                    'metaClass' => 'SIF::AU::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'SIF_Element',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                    'type' => 'normalizedString|http://www.w3.org/2001/XMLSchema'
                                                  }, 'XML::Pastor::Schema::Element' ),
                            'SIF_Operator' => bless( {
                                                     'class' => 'SIF::AU::Type::SIF_QueryDataModelType_SIF_ConditionGroup_SIF_Conditions_SIF_Condition_SIF_Operator',
                                                     'documentation' => bless( [
                                                                                 bless( {
                                                                                          'text' => 'The comparison operator for the condition.'
                                                                                        }, 'XML::Pastor::Schema::Documentation' )
                                                                               ], 'Data::HashArray' ),
                                                     'metaClass' => 'SIF::AU::Pastor::Meta',
                                                     'minOccurs' => '0',
                                                     'name' => 'SIF_Operator',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                     'type' => 'SIF_QueryDataModelType_SIF_ConditionGroup_SIF_Conditions_SIF_Condition_SIF_Operator|http://www.SIFinfo.org/au/datamodel/1.3'
                                                   }, 'XML::Pastor::Schema::Element' ),
                            'SIF_Value' => bless( {
                                                  'class' => 'XML::Pastor::Builtin::string',
                                                  'documentation' => bless( [
                                                                              bless( {
                                                                                       'text' => 'SIF_Value is the data that is used to compare with the value of the element or attribute.
            '
                                                                                     }, 'XML::Pastor::Schema::Documentation' )
                                                                            ], 'Data::HashArray' ),
                                                  'metaClass' => 'SIF::AU::Pastor::Meta',
                                                  'minOccurs' => '0',
                                                  'name' => 'SIF_Value',
                                                  'scope' => 'local',
                                                  'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                  'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'SIF_Element',
                         'SIF_Operator',
                         'SIF_Value'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'SIF_QueryDataModelType_SIF_ConditionGroup_SIF_Conditions_SIF_Condition',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::SIF_QueryDataModelType_SIF_ConditionGroup_SIF_Conditions_SIF_Condition>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<SIF_Element>()      - See L<XML::Pastor::Builtin::normalizedString>.

=item B<SIF_Operator>()      - See L<SIF::AU::Type::SIF_QueryDataModelType_SIF_ConditionGroup_SIF_Conditions_SIF_Condition_SIF_Operator>.

=item B<SIF_Value>()      - See L<XML::Pastor::Builtin::string>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
