
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::StudentParticipationType;

use SIF::AU::Type::AUCodeSetsStudentFamilyProgramTypeType;
use SIF::AU::Type::AUCodeSetsYesOrNoCategoryType;
use SIF::AU::Type::IdRefType;
use SIF::AU::Type::ProgramStatusType;
use SIF::AU::Type::RefIdType;
use SIF::AU::Type::SIF_ExtendedElementsType;
use SIF::AU::Type::SIF_MetadataType;
use SIF::AU::Type::StudentParticipationType_ManagingSchool;
use SIF::AU::Type::StudentParticipationType_ProgramAvailability;
use SIF::AU::Type::StudentParticipationType_ProgramFundingSources;
use SIF::AU::Type::StudentParticipationType_ReferralSource;
use SIF::AU::Type::StudentParticipationType_StudentSpecialEducationFTE;

our @ISA=qw(XML::Pastor::ComplexType);

SIF::AU::Type::StudentParticipationType->mk_accessors( qw(_RefId StudentPersonalRefId StudentParticipationAsOfDate ProgramType ProgramFundingSources ManagingSchool ReferralDate ReferralSource ProgramStatus GiftedEligibilityCriteria EvaluationParentalConsentDate EvaluationDate EvaluationExtensionDate ExtensionComments ReevaluationDate ProgramEligibilityDate ProgramPlanDate ProgramPlanEffectiveDate NOREPDate PlacementParentalConsentDate ProgramPlacementDate ExtendedSchoolYear ExtendedDay ProgramAvailability EntryPerson StudentSpecialEducationFTE ParticipationContact SIF_Metadata SIF_ExtendedElements));

# Attribute accessor aliases

sub RefId { &_RefId; }

SIF::AU::Type::StudentParticipationType->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'RefId' => bless( {
                                                'class' => 'SIF::AU::Type::RefIdType',
                                                'documentation' => bless( [
                                                                            bless( {
                                                                                     'text' => 'This is the unique identification code'
                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                          ], 'Data::HashArray' ),
                                                'metaClass' => 'SIF::AU::Pastor::Meta',
                                                'name' => 'RefId',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                'type' => 'RefIdType|http://www.SIFinfo.org/au/datamodel/1.3',
                                                'use' => 'required'
                                              }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'RefId'
                         ],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SIF::AU::Type::StudentParticipationType',
         'contentType' => 'complex',
         'documentation' => bless( [
                                     bless( {
                                              'text' => 'This object contains information pertaining to student eligibility for and participation in an individualized special program such as special education, ESL, etc.'
                                            }, 'XML::Pastor::Schema::Documentation' )
                                   ], 'Data::HashArray' ),
         'elementInfo' => {
                            'EntryPerson' => bless( {
                                                    'class' => 'XML::Pastor::Builtin::normalizedString',
                                                    'documentation' => bless( [
                                                                                bless( {
                                                                                         'text' => 'Identification / name of the person who created the transaction that led to the creation of this instance of the object.'
                                                                                       }, 'XML::Pastor::Schema::Documentation' )
                                                                              ], 'Data::HashArray' ),
                                                    'metaClass' => 'SIF::AU::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'EntryPerson',
                                                    'nillable' => 'true',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                    'type' => 'normalizedString|http://www.w3.org/2001/XMLSchema'
                                                  }, 'XML::Pastor::Schema::Element' ),
                            'EvaluationDate' => bless( {
                                                       'class' => 'XML::Pastor::Builtin::date',
                                                       'documentation' => bless( [
                                                                                   bless( {
                                                                                            'text' => 'Date the evaluation/assessment process for student was completed.'
                                                                                          }, 'XML::Pastor::Schema::Documentation' )
                                                                                 ], 'Data::HashArray' ),
                                                       'metaClass' => 'SIF::AU::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'EvaluationDate',
                                                       'nillable' => 'true',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                       'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                     }, 'XML::Pastor::Schema::Element' ),
                            'EvaluationExtensionDate' => bless( {
                                                                'class' => 'XML::Pastor::Builtin::date',
                                                                'documentation' => bless( [
                                                                                            bless( {
                                                                                                     'text' => 'Actual date by which evaluation must be completed (for state use in determining timeliness in event that parent and LEA agreed to an extension beyond normal state deadline).'
                                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                                          ], 'Data::HashArray' ),
                                                                'metaClass' => 'SIF::AU::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'EvaluationExtensionDate',
                                                                'nillable' => 'true',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                                'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                              }, 'XML::Pastor::Schema::Element' ),
                            'EvaluationParentalConsentDate' => bless( {
                                                                      'class' => 'XML::Pastor::Builtin::date',
                                                                      'documentation' => bless( [
                                                                                                  bless( {
                                                                                                           'text' => 'Date parent(s) consented to completion of evaluation of child for program participation.'
                                                                                                         }, 'XML::Pastor::Schema::Documentation' )
                                                                                                ], 'Data::HashArray' ),
                                                                      'metaClass' => 'SIF::AU::Pastor::Meta',
                                                                      'minOccurs' => '0',
                                                                      'name' => 'EvaluationParentalConsentDate',
                                                                      'nillable' => 'true',
                                                                      'scope' => 'local',
                                                                      'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                                      'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                                    }, 'XML::Pastor::Schema::Element' ),
                            'ExtendedDay' => bless( {
                                                    'class' => 'XML::Pastor::Builtin::boolean',
                                                    'documentation' => bless( [
                                                                                bless( {
                                                                                         'text' => 'For special education, indicates whether Extended School Day (ESD) services have been determined as necessary.'
                                                                                       }, 'XML::Pastor::Schema::Documentation' )
                                                                              ], 'Data::HashArray' ),
                                                    'metaClass' => 'SIF::AU::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'ExtendedDay',
                                                    'nillable' => 'true',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                    'type' => 'boolean|http://www.w3.org/2001/XMLSchema'
                                                  }, 'XML::Pastor::Schema::Element' ),
                            'ExtendedSchoolYear' => bless( {
                                                           'class' => 'XML::Pastor::Builtin::boolean',
                                                           'documentation' => bless( [
                                                                                       bless( {
                                                                                                'text' => 'For special education, indicates whether Extended School Year (ESY) / summer  services have been determined as necessary'
                                                                                              }, 'XML::Pastor::Schema::Documentation' )
                                                                                     ], 'Data::HashArray' ),
                                                           'metaClass' => 'SIF::AU::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'ExtendedSchoolYear',
                                                           'nillable' => 'true',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                           'type' => 'boolean|http://www.w3.org/2001/XMLSchema'
                                                         }, 'XML::Pastor::Schema::Element' ),
                            'ExtensionComments' => bless( {
                                                          'class' => 'XML::Pastor::Builtin::string',
                                                          'documentation' => bless( [
                                                                                      bless( {
                                                                                               'text' => 'Contains any comments on the extension.  Optional even if an EvaluationExtensionDate is present.'
                                                                                             }, 'XML::Pastor::Schema::Documentation' )
                                                                                    ], 'Data::HashArray' ),
                                                          'metaClass' => 'SIF::AU::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'ExtensionComments',
                                                          'nillable' => 'true',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                          'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                        }, 'XML::Pastor::Schema::Element' ),
                            'GiftedEligibilityCriteria' => bless( {
                                                                  'class' => 'SIF::AU::Type::AUCodeSetsYesOrNoCategoryType',
                                                                  'documentation' => bless( [
                                                                                              bless( {
                                                                                                       'text' => 'Eligible for Gifted / Talented program?'
                                                                                                     }, 'XML::Pastor::Schema::Documentation' )
                                                                                            ], 'Data::HashArray' ),
                                                                  'metaClass' => 'SIF::AU::Pastor::Meta',
                                                                  'minOccurs' => '0',
                                                                  'name' => 'GiftedEligibilityCriteria',
                                                                  'nillable' => 'true',
                                                                  'scope' => 'local',
                                                                  'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                                  'type' => 'AUCodeSetsYesOrNoCategoryType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                                }, 'XML::Pastor::Schema::Element' ),
                            'ManagingSchool' => bless( {
                                                       'class' => 'SIF::AU::Type::StudentParticipationType_ManagingSchool',
                                                       'metaClass' => 'SIF::AU::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'ManagingSchool',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                       'type' => 'StudentParticipationType_ManagingSchool|http://www.SIFinfo.org/au/datamodel/1.3'
                                                     }, 'XML::Pastor::Schema::Element' ),
                            'NOREPDate' => bless( {
                                                  'class' => 'XML::Pastor::Builtin::date',
                                                  'documentation' => bless( [
                                                                              bless( {
                                                                                       'text' => 'Date the Notice of Recommended Educational Placement was signed and approved by the parent / guardian of the student.'
                                                                                     }, 'XML::Pastor::Schema::Documentation' )
                                                                            ], 'Data::HashArray' ),
                                                  'metaClass' => 'SIF::AU::Pastor::Meta',
                                                  'minOccurs' => '0',
                                                  'name' => 'NOREPDate',
                                                  'nillable' => 'true',
                                                  'scope' => 'local',
                                                  'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                  'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                }, 'XML::Pastor::Schema::Element' ),
                            'ParticipationContact' => bless( {
                                                             'class' => 'XML::Pastor::Builtin::normalizedString',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'Primary contact for this record.'
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'SIF::AU::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'ParticipationContact',
                                                             'nillable' => 'true',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                             'type' => 'normalizedString|http://www.w3.org/2001/XMLSchema'
                                                           }, 'XML::Pastor::Schema::Element' ),
                            'PlacementParentalConsentDate' => bless( {
                                                                     'class' => 'XML::Pastor::Builtin::date',
                                                                     'documentation' => bless( [
                                                                                                 bless( {
                                                                                                          'text' => 'Date the parent(s) consented to the proposed placement.'
                                                                                                        }, 'XML::Pastor::Schema::Documentation' )
                                                                                               ], 'Data::HashArray' ),
                                                                     'metaClass' => 'SIF::AU::Pastor::Meta',
                                                                     'minOccurs' => '0',
                                                                     'name' => 'PlacementParentalConsentDate',
                                                                     'nillable' => 'true',
                                                                     'scope' => 'local',
                                                                     'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                                     'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                                   }, 'XML::Pastor::Schema::Element' ),
                            'ProgramAvailability' => bless( {
                                                            'class' => 'SIF::AU::Type::StudentParticipationType_ProgramAvailability',
                                                            'metaClass' => 'SIF::AU::Pastor::Meta',
                                                            'minOccurs' => '0',
                                                            'name' => 'ProgramAvailability',
                                                            'nillable' => 'true',
                                                            'scope' => 'local',
                                                            'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                            'type' => 'StudentParticipationType_ProgramAvailability|http://www.SIFinfo.org/au/datamodel/1.3'
                                                          }, 'XML::Pastor::Schema::Element' ),
                            'ProgramEligibilityDate' => bless( {
                                                               'class' => 'XML::Pastor::Builtin::date',
                                                               'documentation' => bless( [
                                                                                           bless( {
                                                                                                    'text' => 'Date student is eligible for beginning the support program(s).'
                                                                                                  }, 'XML::Pastor::Schema::Documentation' )
                                                                                         ], 'Data::HashArray' ),
                                                               'metaClass' => 'SIF::AU::Pastor::Meta',
                                                               'minOccurs' => '0',
                                                               'name' => 'ProgramEligibilityDate',
                                                               'nillable' => 'true',
                                                               'scope' => 'local',
                                                               'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                               'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                             }, 'XML::Pastor::Schema::Element' ),
                            'ProgramFundingSources' => bless( {
                                                              'class' => 'SIF::AU::Type::StudentParticipationType_ProgramFundingSources',
                                                              'metaClass' => 'SIF::AU::Pastor::Meta',
                                                              'minOccurs' => '0',
                                                              'name' => 'ProgramFundingSources',
                                                              'nillable' => 'true',
                                                              'scope' => 'local',
                                                              'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                              'type' => 'StudentParticipationType_ProgramFundingSources|http://www.SIFinfo.org/au/datamodel/1.3'
                                                            }, 'XML::Pastor::Schema::Element' ),
                            'ProgramPlacementDate' => bless( {
                                                             'class' => 'XML::Pastor::Builtin::date',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'Date student began the support program.'
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'SIF::AU::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'ProgramPlacementDate',
                                                             'nillable' => 'true',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                             'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                           }, 'XML::Pastor::Schema::Element' ),
                            'ProgramPlanDate' => bless( {
                                                        'class' => 'XML::Pastor::Builtin::date',
                                                        'documentation' => bless( [
                                                                                    bless( {
                                                                                             'text' => 'Date the most recent program plan was completed and approved by the team responsible for developing it.  The date the parent consented to placement is NOREPDate.'
                                                                                           }, 'XML::Pastor::Schema::Documentation' )
                                                                                  ], 'Data::HashArray' ),
                                                        'metaClass' => 'SIF::AU::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'ProgramPlanDate',
                                                        'nillable' => 'true',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                        'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                      }, 'XML::Pastor::Schema::Element' ),
                            'ProgramPlanEffectiveDate' => bless( {
                                                                 'class' => 'XML::Pastor::Builtin::date',
                                                                 'documentation' => bless( [
                                                                                             bless( {
                                                                                                      'text' => 'Date by which the plan must be implemented for the student.'
                                                                                                    }, 'XML::Pastor::Schema::Documentation' )
                                                                                           ], 'Data::HashArray' ),
                                                                 'metaClass' => 'SIF::AU::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'ProgramPlanEffectiveDate',
                                                                 'nillable' => 'true',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                                 'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                               }, 'XML::Pastor::Schema::Element' ),
                            'ProgramStatus' => bless( {
                                                      'class' => 'SIF::AU::Type::ProgramStatusType',
                                                      'metaClass' => 'SIF::AU::Pastor::Meta',
                                                      'minOccurs' => '0',
                                                      'name' => 'ProgramStatus',
                                                      'nillable' => 'true',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                      'type' => 'ProgramStatusType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                    }, 'XML::Pastor::Schema::Element' ),
                            'ProgramType' => bless( {
                                                    'class' => 'SIF::AU::Type::AUCodeSetsStudentFamilyProgramTypeType',
                                                    'documentation' => bless( [
                                                                                bless( {
                                                                                         'text' => 'Identifies the individualised program for which the student\'s participation is described in this instance'
                                                                                       }, 'XML::Pastor::Schema::Documentation' )
                                                                              ], 'Data::HashArray' ),
                                                    'metaClass' => 'SIF::AU::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'ProgramType',
                                                    'nillable' => 'true',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                    'type' => 'AUCodeSetsStudentFamilyProgramTypeType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                  }, 'XML::Pastor::Schema::Element' ),
                            'ReevaluationDate' => bless( {
                                                         'class' => 'XML::Pastor::Builtin::date',
                                                         'documentation' => bless( [
                                                                                     bless( {
                                                                                              'text' => 'Date students will be reevaluated for continued placement in a support program(s).'
                                                                                            }, 'XML::Pastor::Schema::Documentation' )
                                                                                   ], 'Data::HashArray' ),
                                                         'metaClass' => 'SIF::AU::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'ReevaluationDate',
                                                         'nillable' => 'true',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                         'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                       }, 'XML::Pastor::Schema::Element' ),
                            'ReferralDate' => bless( {
                                                     'class' => 'XML::Pastor::Builtin::date',
                                                     'documentation' => bless( [
                                                                                 bless( {
                                                                                          'text' => 'Date student was referred for evaluation/program participation.'
                                                                                        }, 'XML::Pastor::Schema::Documentation' )
                                                                               ], 'Data::HashArray' ),
                                                     'metaClass' => 'SIF::AU::Pastor::Meta',
                                                     'minOccurs' => '0',
                                                     'name' => 'ReferralDate',
                                                     'nillable' => 'true',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                     'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                   }, 'XML::Pastor::Schema::Element' ),
                            'ReferralSource' => bless( {
                                                       'class' => 'SIF::AU::Type::StudentParticipationType_ReferralSource',
                                                       'metaClass' => 'SIF::AU::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'ReferralSource',
                                                       'nillable' => 'true',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                       'type' => 'StudentParticipationType_ReferralSource|http://www.SIFinfo.org/au/datamodel/1.3'
                                                     }, 'XML::Pastor::Schema::Element' ),
                            'SIF_ExtendedElements' => bless( {
                                                             'class' => 'SIF::AU::Type::SIF_ExtendedElementsType',
                                                             'metaClass' => 'SIF::AU::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'SIF_ExtendedElements',
                                                             'nillable' => 'true',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                             'type' => 'SIF_ExtendedElementsType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                           }, 'XML::Pastor::Schema::Element' ),
                            'SIF_Metadata' => bless( {
                                                     'class' => 'SIF::AU::Type::SIF_MetadataType',
                                                     'metaClass' => 'SIF::AU::Pastor::Meta',
                                                     'minOccurs' => '0',
                                                     'name' => 'SIF_Metadata',
                                                     'nillable' => 'true',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                     'type' => 'SIF_MetadataType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                   }, 'XML::Pastor::Schema::Element' ),
                            'StudentParticipationAsOfDate' => bless( {
                                                                     'class' => 'XML::Pastor::Builtin::date',
                                                                     'documentation' => bless( [
                                                                                                 bless( {
                                                                                                          'text' => '
        Effective date (NOT the entry date) of this StudentParticipation instance for the identified student and program.
        Each time there is a change to the student\'s program participation profile, a new instance of this object is to be generated with
        the appropriate StudentParticipationAsOfDate and a new RefId.
      '
                                                                                                        }, 'XML::Pastor::Schema::Documentation' )
                                                                                               ], 'Data::HashArray' ),
                                                                     'metaClass' => 'SIF::AU::Pastor::Meta',
                                                                     'minOccurs' => '0',
                                                                     'name' => 'StudentParticipationAsOfDate',
                                                                     'scope' => 'local',
                                                                     'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                                     'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                                   }, 'XML::Pastor::Schema::Element' ),
                            'StudentPersonalRefId' => bless( {
                                                             'class' => 'SIF::AU::Type::IdRefType',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'The GUID of the student that this object is linked to.'
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'SIF::AU::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'StudentPersonalRefId',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                             'type' => 'IdRefType|http://www.SIFinfo.org/au/datamodel/1.3'
                                                           }, 'XML::Pastor::Schema::Element' ),
                            'StudentSpecialEducationFTE' => bless( {
                                                                   'class' => 'SIF::AU::Type::StudentParticipationType_StudentSpecialEducationFTE',
                                                                   'metaClass' => 'SIF::AU::Pastor::Meta',
                                                                   'minOccurs' => '0',
                                                                   'name' => 'StudentSpecialEducationFTE',
                                                                   'nillable' => 'true',
                                                                   'scope' => 'local',
                                                                   'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                                   'type' => 'StudentParticipationType_StudentSpecialEducationFTE|http://www.SIFinfo.org/au/datamodel/1.3'
                                                                 }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'StudentPersonalRefId',
                         'StudentParticipationAsOfDate',
                         'ProgramType',
                         'ProgramFundingSources',
                         'ManagingSchool',
                         'ReferralDate',
                         'ReferralSource',
                         'ProgramStatus',
                         'GiftedEligibilityCriteria',
                         'EvaluationParentalConsentDate',
                         'EvaluationDate',
                         'EvaluationExtensionDate',
                         'ExtensionComments',
                         'ReevaluationDate',
                         'ProgramEligibilityDate',
                         'ProgramPlanDate',
                         'ProgramPlanEffectiveDate',
                         'NOREPDate',
                         'PlacementParentalConsentDate',
                         'ProgramPlacementDate',
                         'ExtendedSchoolYear',
                         'ExtendedDay',
                         'ProgramAvailability',
                         'EntryPerson',
                         'StudentSpecialEducationFTE',
                         'ParticipationContact',
                         'SIF_Metadata',
                         'SIF_ExtendedElements'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'StudentParticipationType',
         'scope' => 'global',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::StudentParticipationType>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

This object contains information pertaining to student eligibility for and participation in an individualized special program such as special education, ESL, etc.


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_RefId>(), B<RefId>()      - See L<SIF::AU::Type::RefIdType>.

=back


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<EntryPerson>()      - See L<XML::Pastor::Builtin::normalizedString>.

=item B<EvaluationDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<EvaluationExtensionDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<EvaluationParentalConsentDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<ExtendedDay>()      - See L<XML::Pastor::Builtin::boolean>.

=item B<ExtendedSchoolYear>()      - See L<XML::Pastor::Builtin::boolean>.

=item B<ExtensionComments>()      - See L<XML::Pastor::Builtin::string>.

=item B<GiftedEligibilityCriteria>()      - See L<SIF::AU::Type::AUCodeSetsYesOrNoCategoryType>.

=item B<ManagingSchool>()      - See L<SIF::AU::Type::StudentParticipationType_ManagingSchool>.

=item B<NOREPDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<ParticipationContact>()      - See L<XML::Pastor::Builtin::normalizedString>.

=item B<PlacementParentalConsentDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<ProgramAvailability>()      - See L<SIF::AU::Type::StudentParticipationType_ProgramAvailability>.

=item B<ProgramEligibilityDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<ProgramFundingSources>()      - See L<SIF::AU::Type::StudentParticipationType_ProgramFundingSources>.

=item B<ProgramPlacementDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<ProgramPlanDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<ProgramPlanEffectiveDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<ProgramStatus>()      - See L<SIF::AU::Type::ProgramStatusType>.

=item B<ProgramType>()      - See L<SIF::AU::Type::AUCodeSetsStudentFamilyProgramTypeType>.

=item B<ReevaluationDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<ReferralDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<ReferralSource>()      - See L<SIF::AU::Type::StudentParticipationType_ReferralSource>.

=item B<SIF_ExtendedElements>()      - See L<SIF::AU::Type::SIF_ExtendedElementsType>.

=item B<SIF_Metadata>()      - See L<SIF::AU::Type::SIF_MetadataType>.

=item B<StudentParticipationAsOfDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<StudentPersonalRefId>()      - See L<SIF::AU::Type::IdRefType>.

=item B<StudentSpecialEducationFTE>()      - See L<SIF::AU::Type::StudentParticipationType_StudentSpecialEducationFTE>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
