
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::StudentPersonalType_AlertMessages;

use SIF::AU::Type::StudentPersonalType_AlertMessages_AlertMessage;

our @ISA=qw(XML::Pastor::ComplexType);

SIF::AU::Type::StudentPersonalType_AlertMessages->mk_accessors( qw(AlertMessage));

SIF::AU::Type::StudentPersonalType_AlertMessages->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SIF::AU::Type::StudentPersonalType_AlertMessages',
         'contentType' => 'complex',
         'elementInfo' => {
                            'AlertMessage' => bless( {
                                                     'class' => 'SIF::AU::Type::StudentPersonalType_AlertMessages_AlertMessage',
                                                     'documentation' => bless( [
                                                                                 bless( {
                                                                                          'text' => 'This is an alert message that is associated with the student.'
                                                                                        }, 'XML::Pastor::Schema::Documentation' )
                                                                               ], 'Data::HashArray' ),
                                                     'maxOccurs' => 'unbounded',
                                                     'metaClass' => 'SIF::AU::Pastor::Meta',
                                                     'minOccurs' => '0',
                                                     'name' => 'AlertMessage',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                     'type' => 'StudentPersonalType_AlertMessages_AlertMessage|http://www.SIFinfo.org/au/datamodel/1.3'
                                                   }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'AlertMessage'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'StudentPersonalType_AlertMessages',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::StudentPersonalType_AlertMessages>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<AlertMessage>()      - See L<SIF::AU::Type::StudentPersonalType_AlertMessages_AlertMessage>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
