
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::SummaryEnrollmentInfoType_SchoolEnrollmentList;

use SIF::AU::Type::SummaryEnrollmentInfoType_SchoolEnrollmentList_SchoolEnrollment;

our @ISA=qw(XML::Pastor::ComplexType);

SIF::AU::Type::SummaryEnrollmentInfoType_SchoolEnrollmentList->mk_accessors( qw(SchoolEnrollment));

SIF::AU::Type::SummaryEnrollmentInfoType_SchoolEnrollmentList->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SIF::AU::Type::SummaryEnrollmentInfoType_SchoolEnrollmentList',
         'contentType' => 'complex',
         'elementInfo' => {
                            'SchoolEnrollment' => bless( {
                                                         'class' => 'SIF::AU::Type::SummaryEnrollmentInfoType_SchoolEnrollmentList_SchoolEnrollment',
                                                         'maxOccurs' => 'unbounded',
                                                         'metaClass' => 'SIF::AU::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'SchoolEnrollment',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                         'type' => 'SummaryEnrollmentInfoType_SchoolEnrollmentList_SchoolEnrollment|http://www.SIFinfo.org/au/datamodel/1.3'
                                                       }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'SchoolEnrollment'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'SummaryEnrollmentInfoType_SchoolEnrollmentList',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::SummaryEnrollmentInfoType_SchoolEnrollmentList>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<SchoolEnrollment>()      - See L<SIF::AU::Type::SummaryEnrollmentInfoType_SchoolEnrollmentList_SchoolEnrollment>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
