
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList_RoleScope;

use SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList_RoleScope_RoleScopeRefId;

our @ISA=qw(XML::Pastor::ComplexType);

SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList_RoleScope->mk_accessors( qw(RoleScopeName RoleScopeRefId));

SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList_RoleScope->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList_RoleScope',
         'contentType' => 'complex',
         'elementInfo' => {
                            'RoleScopeName' => bless( {
                                                      'class' => 'XML::Pastor::Builtin::normalizedString',
                                                      'documentation' => bless( [
                                                                                  bless( {
                                                                                           'text' => 'The group/OU this role is applicable to.'
                                                                                         }, 'XML::Pastor::Schema::Documentation' )
                                                                                ], 'Data::HashArray' ),
                                                      'metaClass' => 'SIF::AU::Pastor::Meta',
                                                      'minOccurs' => '0',
                                                      'name' => 'RoleScopeName',
                                                      'nillable' => 'true',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                      'type' => 'normalizedString|http://www.w3.org/2001/XMLSchema'
                                                    }, 'XML::Pastor::Schema::Element' ),
                            'RoleScopeRefId' => bless( {
                                                       'class' => 'SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList_RoleScope_RoleScopeRefId',
                                                       'metaClass' => 'SIF::AU::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'RoleScopeRefId',
                                                       'nillable' => 'true',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                       'type' => 'SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList_RoleScope_RoleScopeRefId|http://www.SIFinfo.org/au/datamodel/1.3'
                                                     }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'RoleScopeName',
                         'RoleScopeRefId'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList_RoleScope',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList_RoleScope>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<RoleScopeName>()      - See L<XML::Pastor::Builtin::normalizedString>.

=item B<RoleScopeRefId>()      - See L<SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList_RoleScope_RoleScopeRefId>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
