
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Wed Aug  7 12:13:32 2013'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role;

use SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList;

our @ISA=qw(XML::Pastor::ComplexType);

SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role->mk_accessors( qw(_RoleId RoleScopeList));

# Attribute accessor aliases

sub RoleId { &_RoleId; }

SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'RoleId' => bless( {
                                                 'class' => 'XML::Pastor::Builtin::normalizedString',
                                                 'documentation' => bless( [
                                                                             bless( {
                                                                                      'text' => 'Role of the entity this object describes in the SystemContext.'
                                                                                    }, 'XML::Pastor::Schema::Documentation' )
                                                                           ], 'Data::HashArray' ),
                                                 'metaClass' => 'SIF::AU::Pastor::Meta',
                                                 'name' => 'RoleId',
                                                 'scope' => 'local',
                                                 'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                 'type' => 'normalizedString|http://www.w3.org/2001/XMLSchema',
                                                 'use' => 'required'
                                               }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'RoleId'
                         ],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role',
         'contentType' => 'complex',
         'elementInfo' => {
                            'RoleScopeList' => bless( {
                                                      'class' => 'SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList',
                                                      'metaClass' => 'SIF::AU::Pastor::Meta',
                                                      'minOccurs' => '0',
                                                      'name' => 'RoleScopeList',
                                                      'nillable' => 'true',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3',
                                                      'type' => 'SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList|http://www.SIFinfo.org/au/datamodel/1.3'
                                                    }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'RoleScopeList'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SIF::AU::Pastor::Meta',
         'name' => 'SystemRoleType_SystemContextList_SystemContext_RoleList_Role',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://www.SIFinfo.org/au/datamodel/1.3'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Wed Aug  7 12:13:32 2013'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_RoleId>(), B<RoleId>()      - See L<XML::Pastor::Builtin::normalizedString>.

=back


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<RoleScopeList>()      - See L<SIF::AU::Type::SystemRoleType_SystemContextList_SystemContext_RoleList_Role_RoleScopeList>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
